<a href="https://colab.research.google.com/github/Kangminsu3315/D.com_cpp_study/blob/main/9_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import matplotlib as plt

In [3]:
x= torch.ones(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [4]:
x=torch.zeros(3,2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [7]:
torch.manual_seed(2)#시드가 같으면 항상 같은값나옴
x=torch.rand(3,2)
print(x)
x=torch.randn(3,3)#가우시안 분포
print(x)

tensor([[0.6147, 0.3810],
        [0.6371, 0.4745],
        [0.7136, 0.6190]])
tensor([[-2.1409, -0.5534, -0.5000],
        [-0.0815, -0.1633,  1.5277],
        [-0.4023,  0.0972, -0.5682]])


In [9]:
x=torch.tensor([[1,2],
                [3,4],
                [5,6]])
print(x[:,1])
print(x[0,:])
y=x[1,1]
print(y)

tensor([2, 4, 6])
tensor([1, 2])
tensor(4)


In [10]:
y=x.view(2,3)
print(y)
y=x.view(6,-1)#-1은 조커 
print(y)


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [11]:
x=torch.ones(3,2)
y=torch.ones(3,2)
z= x+y
z=torch.add(x,y)
print(z)



tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [13]:
z=x-y
z=torch.sub(x,y)
print(z)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [16]:
x=torch.linspace(0,1,steps=5)#0애서 1사이에 등간격을 가진 5개 
x_np=x.numpy()
print(x)
print(type(x),type(x_np))

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [17]:
a= np.random.randn(5)
a_pt=torch.from_numpy(a)
print(a)
print(type(a),type(a_pt))

[-0.52524484 -0.3842352  -1.74149888  0.41733939 -1.78668109]
<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [2]:
print(torch.cuda.device_count())

1


In [3]:
print(torch.cuda.get_device_name(0))

Tesla T4


In [5]:
cuda0 = torch.device('cuda:0')
a=torch.ones(3,2,device=cuda0)
b=torch.ones(3,2,device=cuda0)
c=a+b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


In [6]:
x=torch.ones([3,2],requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [7]:
y=x+5
print(y)
z=y*y+1
print(z)
t=torch.sum(z)
print(t)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)
tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)
tensor(222., grad_fn=<SumBackward0>)


In [8]:
t.backward()
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])
